name: AI Fact Video Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system tools
        run: |
          sudo apt update
          sudo apt install -y \
            ffmpeg \
            imagemagick \
            piper-tts \
            wget

      - name: Prepare Piper Voice
        run: |
          mkdir -p piper
          cp /usr/bin/piper piper/piper
          chmod +x piper/piper
          wget https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/medium/en_US-lessac-medium.onnx \
            -O piper/en_US-lessac-medium.onnx

      - name: Run bot
        run: python upload.py

      - name: Download video
        uses: actions/upload-artifact@v4
        with:
          name: final-video
          path: final.mp4