name: AI Fact Video Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system tools
        run: |
          sudo apt update
          sudo apt install -y \
            ffmpeg \
            imagemagick \
            wget

      - name: Install Piper TTS
        run: |
          wget https://github.com/rhasspy/piper/releases/latest/download/piper_linux_x86_64.tar.gz
          tar -xzf piper_linux_x86_64.tar.gz
          sudo mv piper /usr/local/bin/
          chmod +x /usr/local/bin/piper
          piper --help

      - name: Prepare Piper Voice
        run: |
          mkdir -p piper
          cp /usr/local/bin/piper piper/piper
          chmod +x piper/piper

          wget https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/medium/en_US-lessac-medium.onnx \
            -O piper/en_US-lessac-medium.onnx

      - name: Run bot
        run: python upload.py

      - name: Download video
        uses: actions/upload-artifact@v4
        with:
          name: final-video
          path: final.mp4