name: AI Fact Video Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system tools
        run: |
          sudo apt update
          sudo apt install -y ffmpeg wget tar

      - name: Download Piper (CORRECT)
        run: |
          mkdir piper
          cd piper
          wget https://github.com/rhasspy/piper/releases/download/v1.2.0/piper_linux_x86_64.tar.gz
          tar -xzf piper_linux_x86_64.tar.gz
          chmod +x piper
          wget https://huggingface.co/rhasspy/piper-voices/resolve/main/en/en_US/lessac/medium/en_US-lessac-medium.onnx

      - name: Run bot
        run: |
          python upload.py

      - name: Download video
        uses: actions/upload-artifact@v4
        with:
          name: final-video
          path: final.mp4